# Обработка ошибок в React

C 16 версии обработка ошибок внутри компонента в хуке жизненного цикла componentDidCatch() больше не происходит – за место этого подхода пришли внешние компонента-предохранители. 

Комонент-предохранитель должен содержать состояние наличия ошибки. В зависимости от состояния предохранитель рендерит либо свои дочерние компоненты, либо запасной компонент ошибки пользователю.

В случае возникновения ошибки в любом дочернем компоненте будут вызваны:
* __`componentDidCatch(error, info)`__ – подходит для измнения состояния ошибки и создания побочных эффектов.
* __`getDerivedStateFromError(error)`__ – может только вернуть объект измененного состояния.
* 
* `error` – объект перехваченной ошибки, выводит имя и описание, стек вызовов.
* `info` – объект с ключом componentStack, содержит информацию о компоненте, в котором произошла ошибка.

__`Предохранитель способен поймать`__ ошибки в конструкторах, рендерах и методах ЖЦ всех дочерних компонентов.

__`Не способны поймать`__ ошибки: внутри самих себя, методов дочерних компонентов, асинхронных функций setTimeout, setInerval, fetch, обработчики событий (их код не внутри рендера) – поэтому без try/catch все еще не обойтись.
